const computerScience = {
    name: "Computer Science",
    levels: [
        {
          name: "Level 100",
          courses: [
            { name: "CSC 102", units: 4, gradePoint: 0 },
            { name: "MAT 121", units: 4, gradePoint: 0 },
            { name: "MAT 111", units: 4, gradePoint: 0 },
            { name: "PHY 102", units: 3, gradePoint: 0 },
            { name: "GES 107", units: 2, gradePoint: 0 },
            { name: "GES 108", units: 2, gradePoint: 0 },
            { name: "STA 115", units: 3, gradePoint: 0 },
            { name: "CSC 103", units: 4, gradePoint: 0 },
            { name: "MAT 141", units: 4, gradePoint: 0 },
            { name: "GES 101", units: 2, gradePoint: 0 },
            { name: "STA 121", units: 3, gradePoint: 0 },
            { name: "PHY 104", units: 3, gradePoint: 0 },
            { name: "PHY 105", units: 3, gradePoint: 0 },
          ],
        },
        {
          name: "Level 200",
          courses: [
            { name: "GES 102", units: 2, gradePoint: 0 },
            { name: "GES 106", units: 2, gradePoint: 0 },
            { name: "GES 201", units: 2, gradePoint: 0 },
            { name: "CSC 213", units: 4, gradePoint: 0 },
            { name: "CSC 222", units: 4, gradePoint: 0 },
            { name: "CSC 235", units: 3, gradePoint: 0 },
            { name: "CSC 293", units: 3, gradePoint: 0 },
            { name: "CSC 231", units: 3, gradePoint: 0 },
            { name: "CSC 236", units: 3, gradePoint: 0 },
            { name: "CSC 242", units: 3, gradePoint: 0 },
            { name: "CSC 272", units: 3, gradePoint: 0 },
            { name: "CSC 299", units: 2, gradePoint: 0 },
            { name: "MAT 213", units: 4, gradePoint: 0 },
            { name: "MAT 223", units: 4, gradePoint: 0 },
            { name: "STA 211", units: 3, gradePoint: 0 },
            { name: "STA 221", units: 3, gradePoint: 0 },
            { name: "CSC 234", units: 3, gradePoint: 0 },
            { name: "MAT 241", units: 4, gradePoint: 0 },
            { name: "MAT 242", units: 4, gradePoint: 0 },
            { name: "MAT 251", units: 4, gradePoint: 0 },
          ],
        },
        {
          name: "Level 300",
          courses: [
            { name: "GES 103", units: 2, gradePoint: 0 },
            { name: "GES 301", units: 2, gradePoint: 0 },
            { name: "CSC 321", units: 3, gradePoint: 0 },
            { name: "CSC 322", units: 2, gradePoint: 0 },
            { name: "CSC 331", units: 3, gradePoint: 0 },
            { name: "CSC 334", units: 4, gradePoint: 0 },
            { name: "CSC 335", units: 4, gradePoint: 0 },
            { name: "CSC 341", units: 4, gradePoint: 0 },
            { name: "CSC 301", units: 3, gradePoint: 0 },
            { name: "CSC 302", units: 3, gradePoint: 0 },
            { name: "CSC 313", units: 4, gradePoint: 0 },
            { name: "CSC 351", units: 3, gradePoint: 0 },
            { name: "CSC 399", units: 2, gradePoint: 0 },
            { name: "MAT 253", units: 4, gradePoint: 0 },
            { name: "MAT 352", units: 4, gradePoint: 0 },
            { name: "CSC 381", units: 3, gradePoint: 0 },
            { name: "MAT 351", units: 4, gradePoint: 0 },
          ],
        },
        {
          name: "Level 400",
          courses: [
            { name: "CSC 472", units: 4, gradePoint: 0 },
            { name: "CSC 412", units: 3, gradePoint: 0 },
            { name: "CSC 421", units: 3, gradePoint: 0 },
            { name: "CSC 431", units: 3, gradePoint: 0 },
            { name: "CSC 475", units: 3, gradePoint: 0 },
            { name: "CSC 476", units: 3, gradePoint: 0 },
            { name: "CSC 499", units: 3, gradePoint: 0 },
          ],
        },
        {
          name: "Level 500",
          courses: [
            { name: "CSC 599", units: 6, gradePoint: 0 },
            { name: "CSC 531", units: 3, gradePoint: 0 },
            { name: "CSC 532", units: 3, gradePoint: 0 },
            { name: "CSC 533", units: 3, gradePoint: 0 },
            { name: "CSC 551", units: 3, gradePoint: 0 },
            { name: "CSC 552", units: 3, gradePoint: 0 },
            { name: "CSC 554", units: 3, gradePoint: 0 },
            { name: "CSC 583", units: 3, gradePoint: 0 },
            { name: "CSC 584", units: 3, gradePoint: 0 },
            { name: "CSC 553", units: 3, gradePoint: 0 },
            { name: "CSC 571", units: 3, gradePoint: 0 },
            { name: "CSC 572", units: 3, gradePoint: 0 },
            { name: "CSC 573", units: 3, gradePoint: 0 },
            { name: "CSC 574", units: 3, gradePoint: 0 },
            { name: "CSC 575", units: 3, gradePoint: 0 },
            { name: "CSC 581", units: 3, gradePoint: 0 },
            { name: "CSC 582", units: 3, gradePoint: 0 },
          ],
        },
      ],
  };
  
  export default computerScience;